language: node_js
os: linux
dist: xenial
services:
  - docker
before_script:
  - touch .env
jobs:
  include:
    - stage: "Dev"
      name: "Server Lint"
      script: docker-compose run server npm run lint
    - script: docker-compose run client npm run lint
      name: "Client Lint"
    - script: docker-compose run server npm test
      name: "Server Test"
    - script: docker-compose run client npm test
      name: "Client Test"
