version: "3"
services: 
    client:
        build: ./client
        tty: true
        ports: 
            - "3000:3000"
        volumes:
            - "./client:/app"
            - "/app/node_modules"
        working_dir: /app
        links:
            - server:server
        command: npm start
        depends_on: 
            - server
    server:
        build: ./server
        tty: true
        working_dir: /server
        ports:
            - "3001:3001"
        volumes:
            - "./server:/server"
            - "/server/node_modules"
        expose:
            - 3001
        depends_on: 
            - db
        links:
            - db:db
        command: npm start
    db:
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: portfolio
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        expose: 
            - 5432

        
